const state={config:null,step:0,service:null,barber:null,time:null};
const times=["09:00","10:00","11:30","13:30","15:00","16:30","18:00","19:00"];
async function boot(){state.config=await fetch("./config/barbershop.json").then(r=>r.json());applyTheme();render()}
function applyTheme(){const t=state.config.theme;for(const [k,v] of Object.entries({"--bg":t.background,"--surface":t.surface,"--text":t.text,"--muted":t.muted,"--accent":t.accent}))document.documentElement.style.setProperty(k,v)}
function money(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v)}
function render(){const app=document.querySelector("#app");if(state.step===4){app.innerHTML=`<div class="shell success"><div class="success-mark">✓</div><h1>Agendamento confirmado</h1><p class="meta">${state.service.name} com ${state.barber.name} às ${state.time}.</p><button class="ghost" id="again">Novo agendamento</button></div>`;document.querySelector("#again").onclick=()=>{state.step=0;state.service=state.barber=state.time=null;render()};return}const pages=[servicesPage,barbersPage,timesPage,confirmPage];app.innerHTML=`<div class="shell"><header class="brand"><strong>${state.config.name}</strong><span class="badge">AGENDA ONLINE</span></header>${pages[state.step]()}</div><div class="bottom"><div class="bottom-inner"><div class="step">Etapa ${state.step+1} de 4</div>${state.step>0?`<div class="summary">${summary()}</div>`:""}<button class="cta" id="next" ${canNext()?"":"disabled"}>${state.step===3?"Confirmar agendamento":"Continuar"}</button></div></div>`;bind()}
function servicesPage(){return `<section class="hero"><h1>Seu próximo corte começa aqui.</h1><p>Escolha o serviço e encontre o melhor horário disponível.</p></section><section class="section"><h2>Serviços</h2><div class="grid">${state.config.services.map(s=>`<button class="card service" data-id="${s.id}" data-selected="${state.service?.id===s.id}"><div class="row"><div><strong>${s.name}</strong><div class="meta">${s.durationMin} min</div></div><span class="price">${money(s.price)}</span></div></button>`).join("")}</div></section>`}
function barbersPage(){return `<section class="hero"><h1>Escolha seu barbeiro.</h1><p>Veja especialidades antes de reservar.</p></section><section class="section"><div class="grid">${state.config.barbers.map(b=>`<button class="card barber" data-id="${b.id}" data-selected="${state.barber?.id===b.id}"><div class="row"><div><strong>${b.name}</strong><div>${b.specialties.map(x=>`<span class="pill">${x}</span>`).join("")}</div></div><span>›</span></div></button>`).join("")}</div></section>`}
function timesPage(){return `<section class="hero"><h1>Escolha o horário.</h1><p>Hoje • horários disponíveis no MVP demonstrativo.</p></section><section class="section"><div class="times">${times.map(t=>`<button class="time ${state.time===t?"selected":""}" data-time="${t}">${t}</button>`).join("")}</div></section>`}
function confirmPage(){return `<section class="hero"><h1>Confirme em segundos.</h1><p>Revise os dados antes de finalizar.</p></section><section class="section"><div class="card"><div class="row"><span class="meta">Serviço</span><strong>${state.service.name}</strong></div><div class="row"><span class="meta">Barbeiro</span><strong>${state.barber.name}</strong></div><div class="row"><span class="meta">Horário</span><strong>${state.time}</strong></div><div class="row"><span class="meta">Valor</span><strong class="price">${money(state.service.price)}</strong></div></div></section>`}
function summary(){const p=[];if(state.service)p.push(`<strong>${state.service.name}</strong>`);if(state.barber)p.push(state.barber.name);if(state.time)p.push(state.time);return p.join(" • ")}
function canNext(){return[!!state.service,!!state.barber,!!state.time,true][state.step]}
function bind(){document.querySelectorAll(".service").forEach(el=>el.onclick=()=>{state.service=state.config.services.find(x=>x.id===el.dataset.id);render()});document.querySelectorAll(".barber").forEach(el=>el.onclick=()=>{state.barber=state.config.barbers.find(x=>x.id===el.dataset.id);render()});document.querySelectorAll(".time").forEach(el=>el.onclick=()=>{state.time=el.dataset.time;render()});document.querySelector("#next").onclick=()=>{if(canNext()){state.step++;render()}}}
boot();
