const token=sessionStorage.getItem("barbearia_token");if(!token)location.replace("./admin.html");
const root=document.querySelector("#manage-app");
const definitions={barbers:{title:"Profissionais",fields:[["name","Nome","text"],["specialties","Especialidades (vírgula)","text"]]},services:{title:"Serviços",fields:[["name","Nome","text"],["description","Descrição","text"],["durationMin","Duração (min)","number"],["price","Preço (R$)","number"]]},products:{title:"Produtos",fields:[["name","Nome","text"],["description","Descrição","text"],["price","Preço (R$)","number"],["stockQty","Estoque","number"]]},bundles:{title:"Combos",fields:[["name","Nome","text"],["description","Descrição","text"],["price","Preço (R$)","number"]]},plans:{title:"Planos",fields:[["name","Nome","text"],["billingPeriod","MONTHLY ou QUARTERLY","text"],["price","Preço (R$)","number"],["validityDays","Validade (dias)","number"],["usesLimit","Quantidade de usos","number"],["priorityDays","Prioridade (dias)","number"]]},customers:{title:"Clientes",fields:[["name","Nome","text"],["phone","WhatsApp","tel"],["email","E-mail","email"]]},users:{title:"Acessos",fields:[["email","E-mail","email"],["password","Senha (10+ caracteres)","password"],["role","Papel: OWNER ou BARBER","text"],["barberId","ID do profissional (BARBER)","text"]]}};
let selected="services",items=[],error=null;
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"content-type":"application/json",authorization:`Bearer ${token}`}});const result=await response.json();if(response.status===401)location.replace("./admin.html");if(!response.ok)throw new Error(result.error?.message||"Falha na operação.");return result}
async function load(){try{items=(await api(`/api/admin/${selected}`)).items;error=null}catch(e){error=e.message}render()}
function render(){const def=definitions[selected];root.innerHTML=`<div class="shell admin-shell"><header class="brand"><div><span class="eyebrow">GESTÃO</span><strong>${def.title}</strong></div><a class="link" href="./admin.html">Agenda</a></header>${error?`<div class="alert">${error}</div>`:""}<div class="manage-tabs">${Object.entries(definitions).map(([key,value])=>`<button data-section="${key}" class="${selected===key?"active":""}">${value.title}</button>`).join("")}</div><button class="cta manage-add" id="add">Adicionar ${def.title.toLowerCase()}</button><section class="section"><div class="grid">${items.length?items.map(item=>`<article class="card"><strong>${item.name}</strong><div class="meta">${item.description||item.email||item.phone||details(item)}</div></article>`).join(""):`<p class="empty">Nenhum cadastro ainda.</p>`}</div></section><dialog id="editor"><form id="resource-form" class="form"><h2>Novo cadastro</h2>${def.fields.map(([name,label,type])=>`<label>${label}<input name="${name}" type="${type}" ${["description","email","priorityDays","stockQty"].includes(name)?"":"required"} ${type==="number"?"min=0 step=0.01":""}></label>`).join("")}<div class="dialog-actions"><button type="button" class="ghost" id="close">Voltar</button><button class="cta" type="submit">Salvar</button></div></form></dialog><nav class="admin-nav"><a href="./admin.html">Agenda</a><a href="./index.html">Nova reserva</a><a class="active" href="./manage.html">Gestão</a></nav></div>`;document.querySelectorAll("[data-section]").forEach(b=>b.onclick=()=>{selected=b.dataset.section;load()});const dialog=document.querySelector("#editor");document.querySelector("#add").onclick=()=>dialog.showModal();document.querySelector("#close").onclick=()=>dialog.close();document.querySelector("#resource-form").onsubmit=save}
function details(item){if(item.priceCents!=null)return `${new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(item.priceCents/100)}${item.durationMin?` • ${item.durationMin} min`:""}`;if(item.specialties)return typeof item.specialties==="string"?JSON.parse(item.specialties).join(" • "):item.specialties.join(" • ");return "Ativo"}
async function save(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));if(data.specialties)data.specialties=data.specialties.split(",").map(x=>x.trim()).filter(Boolean);if(data.price!==undefined){data.priceCents=Math.round(Number(data.price)*100);delete data.price}for(const key of["durationMin","stockQty","validityDays","usesLimit","priorityDays"])if(data[key]!==undefined&&data[key]!=="")data[key]=Number(data[key]);try{await api(`/api/admin/${selected}`,{method:"POST",body:JSON.stringify(data)});document.querySelector("#editor").close();await load()}catch(e){error=e.message;render()}}
load();
